server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1  # redis 主机   (默认 localhost)
    port: 6379       # redis 端口   (默认 6379)
    database: 0      # redis 数据库 (默认 0)
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
